// AUTO-GENERATED by Kinetic Multi-Agent Pipeline — DO NOT EDIT MANUALLY
import React from 'react';
import { Series, Sequence, useCurrentFrame, useVideoConfig, interpolate, spring, Easing, AbsoluteFill } from 'remotion';
import type { CSSProperties } from 'react';

const primaryColor = '#6366f1';
const secondaryColor = '#a78bfa';
const accentColor = '#f59e0b';
const semanticColor = '#3b82f6';
const errorColor = '#ef4444';
const successColor = '#22c55e';
const neutralColor = '#64748b';
const surfaceColor = '#18181b';
const backgroundColor = '#09090b';
const textColor = '#f4f4f5';
const fontFamily = 'Inter';

export const Scene1 = () => {
  const frame = useCurrentFrame();

  // Header animation (Frame 0-30): fades in with an upward slide
  const headerOpacity = interpolate(frame, [0, 20], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  const headerTranslateY = interpolate(frame, [0, 25], [30, 0], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.out(Easing.cubic),
  });

  // Feature grid animation (Frame 15-50): stagger-slide in from the bottom
  const getCardProgress = (delay: number) => {
    return spring({
      frame: frame - delay,
      fps: 30,
      config: {
        damping: 12,
        stiffness: 100,
      },
    });
  };

  const card1Progress = getCardProgress(15);
  const card2Progress = getCardProgress(22);
  const card3Progress = getCardProgress(29);

  // Status badge animation (Frame 30-55): scales up with a soft bounce
  const badgeProgress = spring({
    frame: frame - 30,
    fps: 30,
    config: {
      damping: 10,
      stiffness: 120,
    },
  });

  // Subtle ambient floating motion for background elements
  const floatAnim = Math.sin(frame * 0.05) * 6;

  return (
    <AbsoluteFill
      style={{
        backgroundColor: backgroundColor,
        fontFamily: fontFamily,
        overflow: "hidden",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "flex-start",
        padding: "80px 60px",
      }}
    >
      {/* Background Decorative Gradients / Glows */}
      <div
        style={{
          position: "absolute",
          top: "-100px",
          left: "50%",
          transform: "translateX(-50%)",
          width: "700px",
          height: "350px",
          borderRadius: "50%",
          background: `radial-gradient(circle, ${primaryColor}15 0%, transparent 70%)`,
          filter: "blur(60px)",
          pointerEvents: "none",
        }}
      />

      {/* Interactive Preview Badge / Status Pill */}
      <div
        style={{
          transform: `scale(${Math.max(0, badgeProgress)}) translateY(${floatAnim}px)`,
          opacity: interpolate(frame, [30, 40], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp" }),
          display: "flex",
          alignItems: "center",
          gap: "8px",
          padding: "8px 18px",
          borderRadius: "30px",
          backgroundColor: surfaceColor,
          border: `1px solid ${neutralColor}`,
          boxShadow: `0 8px 24px rgba(0, 0, 0, 0.25)`,
          marginBottom: "32px",
          zIndex: 10,
        }}
      >
        <div
          style={{
            width: "8px",
            height: "8px",
            borderRadius: "50%",
            backgroundColor: successColor,
            boxShadow: `0 0 8px ${successColor}`,
          }}
        />
        <span
          style={{
            color: textColor,
            fontSize: "13px",
            fontWeight: 600,
            letterSpacing: "0.05em",
            textTransform: "uppercase",
          }}
        >
          Next-Gen Architecture v2.4
        </span>
        <span
          style={{
            backgroundColor: `${primaryColor}25`,
            color: primaryColor,
            fontSize: "11px",
            fontWeight: 700,
            padding: "2px 8px",
            borderRadius: "10px",
            marginLeft: "4px",
          }}
        >
          LIVE
        </span>
      </div>

      {/* Centered Headline Block */}
      <div
        style={{
          opacity: headerOpacity,
          transform: `translateY(${headerTranslateY}px)`,
          textAlign: "center",
          maxWidth: "900px",
          marginBottom: "64px",
          zIndex: 10,
        }}
      >
        <h1
          style={{
            color: textColor,
            fontSize: "56px",
            fontWeight: 800,
            lineHeight: 1.15,
            margin: "0 0 20px 0",
            letterSpacing: "-0.02em",
          }}
        >
          Engineered for <span style={{ color: primaryColor }}>Velocity</span> & Precision
        </h1>
        <p
          style={{
            color: secondaryColor,
            fontSize: "20px",
            lineHeight: 1.5,
            margin: 0,
            fontWeight: 400,
          }}
        >
          A unified design system crafted to scale high-impact digital experiences with immaculate motion and component telemetry.
        </p>
      </div>

      {/* Minimalist Three-Feature Grid */}
      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(3, 1fr)",
          gap: "24px",
          width: "100%",
          maxWidth: "1200px",
          zIndex: 10,
        }}
      >
        {/* Feature Card 1 */}
        <div
          style={{
            backgroundColor: surfaceColor,
            borderRadius: "16px",
            padding: "36px 30px",
            border: `1px solid ${neutralColor}`,
            boxShadow: "0 12px 40px rgba(0, 0, 0, 0.3)",
            transform: `translateY(${interpolate(card1Progress, [0, 1], [60, 0])}px)`,
            opacity: card1Progress,
            display: "flex",
            flexDirection: "column",
            position: "relative",
            overflow: "hidden",
          }}
        >
          <div
            style={{
              position: "absolute",
              top: 0,
              left: 0,
              right: 0,
              height: "3px",
              backgroundColor: primaryColor,
            }}
          />
          <div
            style={{
              width: "48px",
              height: "48px",
              borderRadius: "12px",
              backgroundColor: `${primaryColor}15`,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              marginBottom: "24px",
              color: primaryColor,
              fontWeight: 700,
              fontSize: "18px",
            }}
          >
            01
          </div>
          <h3
            style={{
              color: textColor,
              fontSize: "22px",
              fontWeight: 700,
              margin: "0 0 12px 0",
              letterSpacing: "-0.01em",
            }}
          >
            Modular UI Engine
          </h3>
          <p
            style={{
              color: secondaryColor,
              fontSize: "15px",
              lineHeight: 1.6,
              margin: 0,
            }}
          >
            Dynamic layout compositor built for sub-millisecond rendering and seamless state synchronization.
          </p>
        </div>

        {/* Feature Card 2 */}
        <div
          style={{
            backgroundColor: surfaceColor,
            borderRadius: "16px",
            padding: "36px 30px",
            border: `1px solid ${neutralColor}`,
            boxShadow: "0 12px 40px rgba(0, 0, 0, 0.3)",
            transform: `translateY(${interpolate(card2Progress, [0, 1], [60, 0])}px)`,
            opacity: card2Progress,
            display: "flex",
            flexDirection: "column",
            position: "relative",
            overflow: "hidden",
          }}
        >
          <div
            style={{
              position: "absolute",
              top: 0,
              left: 0,
              right: 0,
              height: "3px",
              backgroundColor: accentColor,
            }}
          />
          <div
            style={{
              width: "48px",
              height: "48px",
              borderRadius: "12px",
              backgroundColor: `${accentColor}15`,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              marginBottom: "24px",
              color: accentColor,
              fontWeight: 700,
              fontSize: "18px",
            }}
          >
            02
          </div>
          <h3
            style={{
              color: textColor,
              fontSize: "22px",
              fontWeight: 700,
              margin: "0 0 12px 0",
              letterSpacing: "-0.01em",
            }}
          >
            Kinetic Physics
          </h3>
          <p
            style={{
              color: secondaryColor,
              fontSize: "15px",
              lineHeight: 1.6,
              margin: 0,
            }}
          >
            Spring-based motion parameters configured to deliver organic, cinematic weight to every transition.
          </p>
        </div>

        {/* Feature Card 3 */}
        <div
          style={{
            backgroundColor: surfaceColor,
            borderRadius: "16px",
            padding: "36px 30px",
            border: `1px solid ${neutralColor}`,
            boxShadow: "0 12px 40px rgba(0, 0, 0, 0.3)",
            transform: `translateY(${interpolate(card3Progress, [0, 1], [60, 0])}px)`,
            opacity: card3Progress,
            display: "flex",
            flexDirection: "column",
            position: "relative",
            overflow: "hidden",
          }}
        >
          <div
            style={{
              position: "absolute",
              top: 0,
              left: 0,
              right: 0,
              height: "3px",
              backgroundColor: successColor,
            }}
          />
          <div
            style={{
              width: "48px",
              height: "48px",
              borderRadius: "12px",
              backgroundColor: `${successColor}15`,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              marginBottom: "24px",
              color: successColor,
              fontWeight: 700,
              fontSize: "18px",
            }}
          >
            03
          </div>
          <h3
            style={{
              color: textColor,
              fontSize: "22px",
              fontWeight: 700,
              margin: "0 0 12px 0",
              letterSpacing: "-0.01em",
            }}
          >
            Real-Time Telemetry
          </h3>
          <p
            style={{
              color: secondaryColor,
              fontSize: "15px",
              lineHeight: 1.6,
              margin: 0,
            }}
          >
            Deep diagnostic overlay tracking framerate stability, memory footprint, and asset execution times.
          </p>
        </div>
      </div>
    </AbsoluteFill>
  );
};
export const Scene2 = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  // Header banner scale & opacity: frame 0 -> 25
  const headerProgress = interpolate(frame, [0, 25], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.bezier(0.16, 1, 0.3, 1),
  });

  // Staggered slide for feature cards: starts at frame 15
  const card1Progress = spring({
    frame: frame - 15,
    fps,
    config: { damping: 14, stiffness: 120 },
  });

  const card2Progress = spring({
    frame: frame - 22,
    fps,
    config: { damping: 14, stiffness: 120 },
  });

  const card3Progress = spring({
    frame: frame - 29,
    fps,
    config: { damping: 14, stiffness: 120 },
  });

  // Summary bar pulse at frame 60
  const pulseProgress = interpolate(frame, [60, 75, 90], [1, 1.04, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  const glowOpacity = interpolate(frame, [60, 75], [0, 0.6], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });

  return (
    <div
      style={{
        position: "absolute",
        top: 0,
        left: 0,
        width: "100%",
        height: "100%",
        backgroundColor: backgroundColor,
        fontFamily: fontFamily,
        color: textColor,
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        padding: "60px 80px",
        boxSizing: "border-box",
        overflow: "hidden",
      }}
    >
      {/* Background ambient lighting */}
      <div
        style={{
          position: "absolute",
          top: "-20%",
          left: "50%",
          transform: "translateX(-50%)",
          width: "700px",
          height: "350px",
          background: `radial-gradient(circle, ${primaryColor}15 0%, transparent 70%)`,
          filter: "blur(60px)",
          pointerEvents: "none",
        }}
      />

      {/* Header Banner */}
      <div
        style={{
          opacity: headerProgress,
          transform: `scale(${interpolate(headerProgress, [0, 1], [0.92, 1])})`,
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          textAlign: "center",
          marginBottom: "50px",
          zIndex: 2,
        }}
      >
        {/* Glowing Badge */}
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: "8px",
            backgroundColor: surfaceColor,
            border: `1px solid ${neutralColor}`,
            padding: "6px 16px",
            borderRadius: "20px",
            marginBottom: "16px",
            boxShadow: `0 0 20px ${primaryColor}20`,
          }}
        >
          <div
            style={{
              width: "8px",
              height: "8px",
              borderRadius: "50%",
              backgroundColor: successColor,
              boxShadow: `0 0 8px ${successColor}`,
            }}
          />
          <span
            style={{
              fontSize: "13px",
              fontWeight: 600,
              letterSpacing: "0.05em",
              color: secondaryColor,
              textTransform: "uppercase",
            }}
          >
            Next-Gen Architecture Active
          </span>
        </div>

        {/* Centralized Value Proposition Header */}
        <h1
          style={{
            fontSize: "48px",
            fontWeight: 800,
            lineHeight: 1.15,
            margin: "0 0 16px 0",
            maxWidth: "900px",
            letterSpacing: "-0.02em",
          }}
        >
          Unified Control & Intelligence for{" "}
          <span
            style={{
              background: `linear-gradient(135deg, ${primaryColor}, ${accentColor})`,
              WebkitBackgroundClip: "text",
              WebkitTextFillColor: "transparent",
            }}
          >
            Modern Workflows
          </span>
        </h1>

        <p
          style={{
            fontSize: "18px",
            color: neutralColor,
            margin: 0,
            maxWidth: "600px",
            lineHeight: 1.5,
          }}
        >
          Orchestrate real-time metrics, automated pipelines, and secure scale across distributed clusters instantly.
        </p>
      </div>

      {/* Three-Column Feature Card Grid */}
      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(3, 1fr)",
          gap: "24px",
          width: "100%",
          maxWidth: "1200px",
          zIndex: 2,
        }}
      >
        {/* Card 1 */}
        <div
          style={{
            backgroundColor: surfaceColor,
            border: `1px solid ${neutralColor}`,
            borderRadius: "16px",
            padding: "32px",
            display: "flex",
            flexDirection: "column",
            justifyContent: "space-between",
            opacity: card1Progress,
            transform: `translateY(${interpolate(card1Progress, [0, 1], [40, 0])}px)`,
            boxShadow: "0 10px 30px rgba(0,0,0,0.2)",
          }}
        >
          <div>
            <div
              style={{
                width: "48px",
                height: "48px",
                borderRadius: "12px",
                backgroundColor: `${primaryColor}15`,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                marginBottom: "20px",
                color: primaryColor,
              }}
            >
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M12 2v20M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6" />
              </svg>
            </div>
            <h3 style={{ fontSize: "20px", fontWeight: 700, margin: "0 0 10px 0" }}>
              Dynamic Telemetry
            </h3>
            <p style={{ fontSize: "14px", color: neutralColor, margin: 0, lineHeight: 1.6 }}>
              Sub-millisecond stream ingestion with automated anomaly detection algorithms.
            </p>
          </div>
          <div style={{ marginTop: "24px", display: "flex", alignItems: "center", gap: "8px" }}>
            <span style={{ fontSize: "12px", color: successColor, fontWeight: 600, backgroundColor: `${successColor}15`, padding: "4px 8px", borderRadius: "6px" }}>
              +99.98% SLA
            </span>
          </div>
        </div>

        {/* Card 2 */}
        <div
          style={{
            backgroundColor: surfaceColor,
            border: `1px solid ${neutralColor}`,
            borderRadius: "16px",
            padding: "32px",
            display: "flex",
            flexDirection: "column",
            justifyContent: "space-between",
            opacity: card2Progress,
            transform: `translateY(${interpolate(card2Progress, [0, 1], [40, 0])}px)`,
            boxShadow: "0 10px 30px rgba(0,0,0,0.2)",
          }}
        >
          <div>
            <div
              style={{
                width: "48px",
                height: "48px",
                borderRadius: "12px",
                backgroundColor: `${accentColor}15`,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                marginBottom: "20px",
                color: accentColor,
              }}
            >
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <rect x="2" y="3" width="20" height="14" rx="2" ry="2" />
                <line x1="8" y1="21" x2="16" y2="21" />
                <line x1="12" y1="17" x2="12" y2="21" />
              </svg>
            </div>
            <h3 style={{ fontSize: "20px", fontWeight: 700, margin: "0 0 10px 0" }}>
              Edge Synchronization
            </h3>
            <p style={{ fontSize: "14px", color: neutralColor, margin: 0, lineHeight: 1.6 }}>
              Decentralized state management ensuring zero-latency cross-region validation.
            </p>
          </div>
          <div style={{ marginTop: "24px", display: "flex", alignItems: "center", gap: "8px" }}>
            <span style={{ fontSize: "12px", color: semanticColor, fontWeight: 600, backgroundColor: `${semanticColor}15`, padding: "4px 8px", borderRadius: "6px" }}>
              Global Mesh
            </span>
          </div>
        </div>

        {/* Card 3 */}
        <div
          style={{
            backgroundColor: surfaceColor,
            border: `1px solid ${neutralColor}`,
            borderRadius: "16px",
            padding: "32px",
            display: "flex",
            flexDirection: "column",
            justifyContent: "space-between",
            opacity: card3Progress,
            transform: `translateY(${interpolate(card3Progress, [0, 1], [40, 0])}px)`,
            boxShadow: "0 10px 30px rgba(0,0,0,0.2)",
          }}
        >
          <div>
            <div
              style={{
                width: "48px",
                height: "48px",
                borderRadius: "12px",
                backgroundColor: `${secondaryColor}15`,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                marginBottom: "20px",
                color: secondaryColor,
              }}
            >
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
              </svg>
            </div>
            <h3 style={{ fontSize: "20px", fontWeight: 700, margin: "0 0 10px 0" }}>
              Zero-Trust Security
            </h3>
            <p style={{ fontSize: "14px", color: neutralColor, margin: 0, lineHeight: 1.6 }}>
              Automated cryptographic enforcement safeguarding every microservice boundary.
            </p>
          </div>
          <div style={{ marginTop: "24px", display: "flex", alignItems: "center", gap: "8px" }}>
            <span style={{ fontSize: "12px", color: successColor, fontWeight: 600, backgroundColor: `${successColor}15`, padding: "4px 8px", borderRadius: "6px" }}>
              Encrypted
            </span>
          </div>
        </div>
      </div>

      {/* Summary Bar Pulsing Green at frame 60 */}
      <div
        style={{
          marginTop: "40px",
          width: "100%",
          maxWidth: "1200px",
          backgroundColor: surfaceColor,
          border: `1px solid ${successColor}`,
          borderRadius: "12px",
          padding: "16px 24px",
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          transform: `scale(${pulseProgress})`,
          boxShadow: `0 0 ${glowOpacity * 30}px ${successColor}40`,
          zIndex: 2,
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
          <div
            style={{
              width: "10px",
              height: "10px",
              borderRadius: "50%",
              backgroundColor: successColor,
              boxShadow: `0 0 10px ${successColor}`,
            }}
          />
          <span style={{ fontSize: "15px", fontWeight: 600, color: textColor }}>
            System Diagnostic Complete: All Subsystems Operational & Synchronized
          </span>
        </div>
        <span style={{ fontSize: "13px", color: successColor, fontWeight: 700 }}>
          READY FOR DEPLOYMENT
        </span>
      </div>
    </div>
  );
};
export const Scene3 = () => {
  const frame = useCurrentFrame();
  const fps = 30;

  // Frame animations
  // Hero headline scale & opacity: frames 0 to 15
  const heroProgress = interpolate(frame, [0, 15], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: Easing.bezier(0.16, 1, 0.3, 1),
  });

  // Value proposition bullets stagger: frames 15 to 45
  const bullet1Progress = interpolate(frame, [15, 27], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: Easing.out(Easing.cubic) });
  const bullet2Progress = interpolate(frame, [22, 34], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: Easing.out(Easing.cubic) });
  const bullet3Progress = interpolate(frame, [29, 41], [0, 1], { extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: Easing.out(Easing.cubic) });

  // CTA button pulse starting at frame 30
  const pulseAnim = Math.sin(Math.max(0, frame - 30) * 0.15);
  const pulseScale = 1 + (frame >= 30 ? pulseAnim * 0.03 : 0);

  // Animated cursor clicking the button at frame 60
  // Cursor moves from bottom-right into the button center between frames 45 and 60, clicks down at 60
  const cursorX = interpolate(frame, [40, 60], [250, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: Easing.bezier(0.25, 1, 0.5, 1) });
  const cursorY = interpolate(frame, [40, 60], [180, 0], { extrapolateLeft: "clamp", extrapolateRight: "clamp", easing: Easing.bezier(0.25, 1, 0.5, 1) });
  const isClicked = frame >= 60 && frame < 68;
  const clickScale = isClicked ? 0.94 : 1;

  return (
    <div
      style={{
        position: "relative",
        width: "1080px",
        height: "1920px",
        backgroundColor: backgroundColor,
        fontFamily: fontFamily,
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        overflow: "hidden",
        padding: "80px 60px",
      }}
    >
      {/* Background ambient lighting / glow elements */}
      <div
        style={{
          position: "absolute",
          top: "15%",
          left: "50%",
          transform: "translate(-50%, -50%)",
          width: "700px",
          height: "700px",
          borderRadius: "50%",
          background: `radial-gradient(circle, ${primaryColor}22 0%, transparent 70%)`,
          filter: "blur(80px)",
          pointerEvents: "none",
        }}
      />
      
      <div
        style={{
          position: "absolute",
          bottom: "10%",
          right: "10%",
          width: "500px",
          height: "500px",
          borderRadius: "50%",
          background: `radial-gradient(circle, ${secondaryColor}15 0%, transparent 70%)`,
          filter: "blur(90px)",
          pointerEvents: "none",
        }}
      />

      {/* Top Header / Metric Pill */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: "12px",
          backgroundColor: surfaceColor,
          padding: "12px 28px",
          borderRadius: "100px",
          border: `1px solid ${neutralColor}`,
          marginBottom: "40px",
          opacity: heroProgress,
          transform: `translateY(${(1 - heroProgress) * -20}px)`,
          boxShadow: "0 20px 40px rgba(0,0,0,0.3)",
        }}
      >
        <span
          style={{
            display: "inline-block",
            width: "10px",
            height: "10px",
            borderRadius: "50%",
            backgroundColor: successColor,
            boxShadow: `0 0 12px ${successColor}`,
          }}
        />
        <span
          style={{
            color: textColor,
            fontSize: "20px",
            fontWeight: 600,
            letterSpacing: "1px",
            textTransform: "uppercase",
          }}
        >
          Next-Gen Studio Ecosystem v4.2
        </span>
      </div>

      {/* Centered Vertical Card Container */}
      <div
        style={{
          width: "100%",
          maxWidth: "920px",
          backgroundColor: surfaceColor,
          borderRadius: "48px",
          border: `1px solid ${neutralColor}`,
          padding: "80px 70px",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          boxShadow: "0 40px 100px rgba(0, 0, 0, 0.5), 0 0 0 1px rgba(255, 255, 255, 0.05) inset",
          position: "relative",
          backdropFilter: "blur(20px)",
        }}
      >
        {/* SVG Badge / Icon */}
        <div
          style={{
            width: "90px",
            height: "90px",
            borderRadius: "28px",
            backgroundColor: `${primaryColor}18`,
            border: `1px solid ${primaryColor}44`,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            marginBottom: "40px",
            opacity: heroProgress,
            transform: `scale(${heroProgress})`,
            boxShadow: `0 0 30px ${primaryColor}33`,
          }}
        >
          <svg width="44" height="44" viewBox="0 0 24 24" fill="none" stroke={primaryColor} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <polygon points="12 2 2 7 12 12 22 7 12 2"></polygon>
            <polyline points="2 17 12 22 22 17"></polyline>
            <polyline points="2 12 12 17 22 12"></polyline>
          </svg>
        </div>

        {/* Hero Headline */}
        <h1
          style={{
            fontSize: "64px",
            fontWeight: 800,
            color: textColor,
            textAlign: "center",
            lineHeight: 1.15,
            margin: "0 0 24px 0",
            opacity: heroProgress,
            transform: `scale(${0.9 + heroProgress * 0.1}) translateY(${(1 - heroProgress) * 30}px)`,
            letterSpacing: "-1.5px",
          }}
        >
          Architecting the Future of <span style={{ color: primaryColor, textShadow: `0 0 40px ${primaryColor}66` }}>Motion Design</span>
        </h1>

        {/* Subtitle description */}
        <p
          style={{
            fontSize: "24px",
            color: neutralColor,
            textAlign: "center",
            lineHeight: 1.5,
            margin: "0 0 60px 0",
            maxWidth: "720px",
            opacity: heroProgress,
            transform: `translateY(${(1 - heroProgress) * 20}px)`,
          }}
        >
          Deploy cinematic-grade animations and interactive UI components directly into your workflow with absolute precision.
        </p>

        {/* Divider */}
        <div
          style={{
            width: "100%",
            height: "1px",
            backgroundColor: neutralColor,
            opacity: 0.2,
            marginBottom: "60px",
          }}
        />

        {/* Value Proposition Bullets */}
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            gap: "28px",
            width: "100%",
            marginBottom: "60px",
          }}
        >
          {/* Bullet 1 */}
          <div
            style={{
              display: "flex",
              alignItems: "center",
              gap: "24px",
              backgroundColor: backgroundColor,
              padding: "24px 32px",
              borderRadius: "24px",
              border: `1px solid ${neutralColor}44`,
              opacity: bullet1Progress,
              transform: `translateY(${(1 - bullet1Progress) * 40}px)`,
            }}
          >
            <div
              style={{
                width: "40px",
                height: "40px",
                borderRadius: "12px",
                backgroundColor: `${successColor}22`,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                flexShrink: 0,
              }}
            >
              <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke={successColor} strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
                <polyline points="20 6 9 17 4 12"></polyline>
              </svg>
            </div>
            <div style={{ display: "flex", flexDirection: "column", gap: "4px" }}>
              <span style={{ fontSize: "22px", fontWeight: 700, color: textColor }}>Sub-Millisecond 60FPS Rendering</span>
              <span style={{ fontSize: "16px", color: neutralColor }}>Engineered with native Remotion and optimized GPU shaders.</span>
            </div>
          </div>

          {/* Bullet 2 */}
          <div
            style={{
              display: "flex",
              alignItems: "center",
              gap: "24px",
              backgroundColor: backgroundColor,
              padding: "24px 32px",
              borderRadius: "24px",
              border: `1px solid ${neutralColor}44`,
              opacity: bullet2Progress,
              transform: `translateY(${(1 - bullet2Progress) * 40}px)`,
            }}
          >
            <div
              style={{
                width: "40px",
                height: "40px",
                borderRadius: "12px",
                backgroundColor: `${primaryColor}22`,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                flexShrink: 0,
              }}
            >
              <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke={primaryColor} strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
                <polyline points="20 6 9 17 4 12"></polyline>
              </svg>
            </div>
            <div style={{ display: "flex", flexDirection: "column", gap: "4px" }}>
              <span style={{ fontSize: "22px", fontWeight: 700, color: textColor }}>Dynamic Design Token Mapping</span>
              <span style={{ fontSize: "16px", color: neutralColor }}>Automatically adapt palettes, typography, and glowing borders.</span>
            </div>
          </div>

          {/* Bullet 3 */}
          <div
            style={{
              display: "flex",
              alignItems: "center",
              gap: "24px",
              backgroundColor: backgroundColor,
              padding: "24px 32px",
              borderRadius: "24px",
              border: `1px solid ${neutralColor}44`,
              opacity: bullet3Progress,
              transform: `translateY(${(1 - bullet3Progress) * 40}px)`,
            }}
          >
            <div
              style={{
                width: "40px",
                height: "40px",
                borderRadius: "12px",
                backgroundColor: `${secondaryColor}22`,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                flexShrink: 0,
              }}
            >
              <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke={secondaryColor} strokeWidth="3" strokeLinecap="round" strokeLinejoin="round">
                <polyline points="20 6 9 17 4 12"></polyline>
              </svg>
            </div>
            <div style={{ display: "flex", flexDirection: "column", gap: "4px" }}>
              <span style={{ fontSize: "22px", fontWeight: 700, color: textColor }}>Production-Ready Component Suite</span>
              <span style={{ fontSize: "16px", color: neutralColor }}>Drop-in standalone TSX scenes built for enterprise delivery.</span>
            </div>
          </div>
        </div>

        {/* Dual-Button Conversion Footer */}
        <div
          style={{
            display: "flex",
            gap: "20px",
            width: "100%",
            marginTop: "10px",
            opacity: bullet3Progress,
          }}
        >
          {/* Secondary CTA Button */}
          <div
            style={{
              flex: 1,
              height: "80px",
              borderRadius: "20px",
              backgroundColor: backgroundColor,
              border: `2px solid ${neutralColor}`,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              cursor: "pointer",
              transition: "all 0.2s ease",
            }}
          >
            <span style={{ fontSize: "20px", fontWeight: 700, color: textColor }}>
              View Documentation
            </span>
          </div>

          {/* Primary CTA Button with Pulse & Click States */}
          <div
            style={{
              flex: 1,
              height: "80px",
              borderRadius: "20px",
              backgroundColor: primaryColor,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              cursor: "pointer",
              transform: `scale(${pulseScale * clickScale})`,
              boxShadow: isClicked 
                ? `0 5px 15px ${primaryColor}44` 
                : `0 20px 50px ${primaryColor}66, 0 0 0 ${isClicked ? '8px' : '0px'} ${backgroundColor}`,
              position: "relative",
              transition: "transform 0.1s ease",
            }}
          >
            <span style={{ fontSize: "20px", fontWeight: 700, color: backgroundColor }}>
              Initialize Pipeline
            </span>

            {/* Animated Cursor */}
            {frame >= 40 && (
              <div
                style={{
                  position: "absolute",
                  bottom: "-60px",
                  right: "-40px",
                  transform: `translate(${cursorX}px, ${cursorY}px) scale(${isClicked ? 0.85 : 1})`,
                  pointerEvents: "none",
                  zIndex: 100,
                  filter: "drop-shadow(0 10px 15px rgba(0,0,0,0.5))",
                }}
              >
                <svg width="48" height="48" viewBox="0 0 24 24" fill={textColor} stroke={backgroundColor} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <polygon points="3 3 10.07 19.97 12.58 12.58 19.97 10.07 3 3"></polygon>
                </svg>
                {isClicked && (
                  <div
                    style={{
                      position: "absolute",
                      top: "0",
                      left: "0",
                      width: "48px",
                      height: "48px",
                      borderRadius: "50%",
                      backgroundColor: `${primaryColor}`,
                      animation: "ping 0.4s cubic-bezier(0, 0, 0.2, 1) infinite",
                      opacity: 0.7,
                    }}
                  />
                )}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export const VideoComposition: React.FC<{ bgSelection?: any }> = ({ bgSelection }) => {
  const bgColor = bgSelection?.color || '#0A0A0F';
  const bgType = bgSelection?.type || 'color';

  let backdropStyle: React.CSSProperties = { backgroundColor: bgColor };
  if (bgType === 'gradient' && bgSelection?.gradient) {
    backdropStyle = { background: bgSelection.gradient };
  } else if (bgType === 'image' && bgSelection?.imageUrl) {
    backdropStyle = { backgroundImage: `url(${bgSelection.imageUrl})`, backgroundSize: 'cover', backgroundPosition: 'center' };
  }

  return (
    <div className="w-full h-full text-white relative overflow-hidden">
      <div style={backdropStyle} className="absolute inset-0 pointer-events-none z-0" />
      <div className="relative z-10 w-full h-full">
        <Series>
        <Series.Sequence durationInFrames={100}>
          <Scene1 />
        </Series.Sequence>
        <Series.Sequence durationInFrames={100}>
          <Scene2 />
        </Series.Sequence>
        <Series.Sequence durationInFrames={100}>
          <Scene3 />
        </Series.Sequence>
        </Series>
      </div>
    </div>
  );
};

export default VideoComposition;