// AUTO-GENERATED by Kinetic Multi-Agent Pipeline — DO NOT EDIT MANUALLY
import React from 'react';
import { Series, useCurrentFrame } from 'remotion';
import { BrowserFrame, HeroMetricCard, SidebarLayout, SplitHeroLayout } from '../primitives/StructuralSDK';
import { BarChartCard } from '../primitives/ChartsSDK';
import { PulseScale, SlideInOut } from '../primitives/TransitionSDK';

const Scene1: React.FC = () => {
  return (
    <div
      style={{
        width: '100%',
        height: '100%',
        position: 'relative',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 32,
        backgroundColor: '#1A1D23',
        fontFamily: 'Inter, Inter, sans-serif',
        overflow: 'hidden',
      }}
    >
      {/* HeroMetricCard */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <SlideInOut direction="bottom" distance={80} duration={24} fade={true}>
          <HeroMetricCard
            title="Revenue Growth"
            value="12.5%"
            change="+2.1%"
            trend="up"
            chartType="mini-line"
            sparklineData={[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]}
            backgroundColor="#2F343E"
            borderRadius={10}
            glowConfig={{ enabled: true, color: "#F7B928", intensity: 8, spread: 4 }}
            rotateX={20}
            rotateZ={10}
            perspective={1000}
            translateX={50}
            translateY={50}
          >
            <div style={{
              fontSize: 14,
              color: "#C7C5C5",
              fontFamily: "Inter",
            }}>
              <div style={{
                fontSize: 18,
                color: "#C7C5C5",
                fontFamily: "Inter",
                marginBottom: 4,
              }}>
                Revenue Growth
              </div>
              <div style={{
                fontSize: 24,
                color: "#F7B928",
                fontFamily: "Inter",
                marginBottom: 4,
              }}>
                12.5%
              </div>
              <div style={{
                fontSize: 14,
                color: "#C7C5C5",
                fontFamily: "Inter",
              }}>
                +2.1% (Last 30 days)
              </div>
            </div>
          </HeroMetricCard>
        </SlideInOut>
      </div>

      {/* SplitHeroLayout */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <PulseScale cycleFrames={90} minScale={0.97} maxScale={1.03}>
          <SplitHeroLayout
            leftPanel={
              <div
                style={{
                  width: 400,
                  height: 200,
                  backgroundColor: "#2F343E",
                  borderRadius: 16,
                  padding: 24,
                  display: "flex",
                  flexDirection: "column",
                  justifyContent: "center",
                  alignItems: "center",
                  fontFamily: "Inter",
                  color: "#C7C5C5",
                }}
              >
                <h2 style={{ fontSize: 24, marginBottom: 8 }}>GuardRail</h2>
                <p style={{ fontSize: 16, marginBottom: 16 }}>Your personalized safety net</p>
                <button
                  style={{
                    backgroundColor: "#F7B928",
                    color: "#1A1D23",
                    border: "none",
                    padding: 12,
                    borderRadius: 8,
                    cursor: "pointer",
                  }}
                >
                  Learn More
                </button>
              </div>
            }
            rightPanel={
              <div
                style={{
                  width: 400,
                  height: 200,
                  backgroundColor: "#2F343E",
                  borderRadius: 16,
                  padding: 24,
                  display: "flex",
                  flexDirection: "column",
                  justifyContent: "center",
                  alignItems: "center",
                  fontFamily: "Inter",
                  color: "#C7C5C5",
                }}
              >
                <h2 style={{ fontSize: 24, marginBottom: 8 }}>Metric Card</h2>
                <p style={{ fontSize: 16, marginBottom: 16 }}>
                  Your progress: <span style={{ color: "#F7B928" }}>78%</span>
                </p>
                <p style={{ fontSize: 16, marginBottom: 16 }}>
                  Trend: <span style={{ color: "#C5C9C7" }}>Up 12%</span>
                </p>
              </div>
            }
            leftWidth="50%"
            rightWidth="50%"
            gap={16}
            alignVertical="center"
            glowConfig={{ enabled: true, color: "#F7B928", intensity: 8, spread: 4 }}
          />
        </PulseScale>
      </div>
    </div>
  );
};

const Scene2: React.FC = () => {
  return (
    <div
      style={{
        width: '100%',
        height: '100%',
        position: 'relative',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 32,
        backgroundColor: '#1A1D23',
        fontFamily: 'Inter, Inter, sans-serif',
        overflow: 'hidden',
      }}
    >
      {/* BarChartCard */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <SlideInOut direction="bottom" distance={80} duration={24} fade={true}>
          <BarChartCard
            title="Threat Detections"
            categories={['Malware', 'Phishing', 'Ransomware', 'SQL Injection']}
            values={[120, 90, 80, 60]}
            barColor="#C7C5C5"
            animated={true}
            width={600}
            height={400}
            showGrid={true}
            showYAxis={true}
            glowConfig={{ enabled: true, color: '#F7B928', intensity: 8, spread: 4 }}
            rotateX={10}
            rotateY={-10}
            perspective={1000}
            translateZ={200}
            backgroundColor="#1A1D23"
            textColor="#C7C5C5"
            surfaceColor="#2F343E"
          >
            <div style={{ fontFamily: 'Inter', fontSize: 14, color: '#C7C5C5' }}>
              <div>Malware: 120</div>
              <div>Phishing: 90</div>
              <div>Ransomware: 80</div>
              <div>SQL Injection: 60</div>
            </div>
          </BarChartCard>
        </SlideInOut>
      </div>
    </div>
  );
};

const Scene3: React.FC = () => {
  return (
    <div
      style={{
        width: '100%',
        height: '100%',
        position: 'relative',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 32,
        backgroundColor: '#1A1D23',
        fontFamily: 'Inter, Inter, sans-serif',
        overflow: 'hidden',
      }}
    >
      {/* BrowserFrame */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <PulseScale cycleFrames={90} minScale={0.97} maxScale={1.03}>
          <BrowserFrame
            url="https://example.com"
            osType="mac"
            width={600}
            height={400}
            backgroundColor="#1A1D23"
            windowBarColor="#2F343E"
            borderRadius={10}
            showNavArrow={true}
            showNewTabButton={true}
            glowConfig={{ enabled: true, color: "#C5C9C7", intensity: 8, spread: 4 }}
            rotateX={10}
            rotateY={-10}
          >
            <div style={{
              fontSize: 24,
              color: "#C7C5C5",
              fontWeight: 600,
            }}>
              Preview GuardRail
            </div>
            <div style={{
              fontSize: 18,
              color: "#C7C5C5",
              marginTop: 10,
            }}>
              GuardRail is a feature that helps prevent accidents on the road.
            </div>
            <div style={{
              fontSize: 18,
              color: "#C7C5C5",
              marginTop: 10,
            }}>
              It uses a combination of sensors and machine learning to detect potential hazards.
            </div>
            <div style={{
              fontSize: 18,
              color: "#C7C5C5",
              marginTop: 10,
            }}>
              GuardRail is designed to be easy to use and understand, with clear and concise instructions.
            </div>
          </BrowserFrame>
        </PulseScale>
      </div>

      {/* SidebarLayout */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <PulseScale cycleFrames={90} minScale={0.97} maxScale={1.03}>
          <SidebarLayout
            appName="GuardRail"
            appLogo="https://example.com/guardrail-logo.png"
            menuItems={[
              { id: "dashboard", label: "Dashboard", active: true },
              { id: "settings", label: "Settings" },
              { id: "help", label: "Help" },
            ]}
            activeMenuItemId="dashboard"
            profileName="John Doe"
            profileHandle="@johndoe"
            profileAvatar="https://example.com/johndoe-avatar.png"
            sidebarContent="Overview of GuardRail features and benefits"
            sidebarWidth={600}
            width={700}
            height={900}
            backgroundColor="#2F343E"
            borderRadius={10}
            glowConfig={{ enabled: true, color: "#F7B928", intensity: 8, spread: 4 }}
          >
            <div style={{ padding: 20, backgroundColor: "#2F343E", borderRadius: 10 }}>
              <h2 style={{ fontSize: 24, color: "#F7B928", fontWeight: 600, marginBottom: 10 }}>
                GuardRail Overview
              </h2>
              <p style={{ fontSize: 18, color: "#C7C5C5", marginBottom: 20 }}>
                GuardRail is a comprehensive platform for monitoring and analyzing web traffic.
              </p>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                <div style={{ display: "flex", alignItems: "center" }}>
                  <span style={{ fontSize: 18, color: "#C7C5C5" }}>Traffic Analysis</span>
                </div>
                <div style={{ display: "flex", alignItems: "center" }}>
                  <span style={{ fontSize: 18, color: "#C7C5C5" }}>Traffic Trends</span>
                </div>
              </div>
            </div>
          </SidebarLayout>
        </PulseScale>
      </div>
    </div>
  );
};

export const VideoComposition: React.FC<{ bgSelection?: any }> = ({ bgSelection }) => {
  const bgColor = bgSelection?.color || '#1A1D23';
  const bgType = bgSelection?.type || 'color';

  let backdropStyle: React.CSSProperties = { backgroundColor: bgColor };
  if (bgType === 'gradient' && bgSelection?.gradient) {
    backdropStyle = { background: bgSelection.gradient };
  } else if (bgType === 'image' && bgSelection?.imageUrl) {
    backdropStyle = { backgroundImage: `url(${bgSelection.imageUrl})`, backgroundSize: 'cover', backgroundPosition: 'center' };
  }

  return (
    <div className="w-full h-full text-white relative overflow-hidden">
      <div style={backdropStyle} className="absolute inset-0 pointer-events-none z-0" />
      <div className="relative z-10 w-full h-full">
        <Series>
          <Series.Sequence durationInFrames={120}>
            <Scene1 />
          </Series.Sequence>
          <Series.Sequence durationInFrames={150}>
            <Scene2 />
          </Series.Sequence>
          <Series.Sequence durationInFrames={90}>
            <Scene3 />
          </Series.Sequence>
        </Series>
      </div>
    </div>
  );
};

export default VideoComposition;