// AUTO-GENERATED by Kinetic Multi-Agent Pipeline — DO NOT EDIT MANUALLY
import React from "react";
import { Series, useCurrentFrame, interpolate } from "remotion";

export const Scene1: React.FC = () => {
  const frame = useCurrentFrame();
  const opacity = interpolate(frame, [0, 20], [0, 1], {
    extrapolateRight: "clamp",
  });
  return (
    <div
      style={{
        width: "100%",
        height: "100%",
        backgroundColor: "#07070d",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        opacity,
      }}
    >
      <div
        style={{
          color: "#64748b",
          fontFamily: "Inter, sans-serif",
          fontSize: 32,
          letterSpacing: 2,
        }}
      >
        Generate a video to see it here
      </div>
    </div>
  );
};

export const VideoComposition: React.FC<{ bgSelection?: any }> = ({
  bgSelection,
}) => {
  const bgColor = bgSelection?.color || "#07080C";
  const bgType = bgSelection?.type || "color";

  let backdropStyle: React.CSSProperties = { backgroundColor: bgColor };
  if (bgType === "gradient" && bgSelection?.gradient) {
    backdropStyle = { background: bgSelection.gradient };
  } else if (bgType === "image" && bgSelection?.imageUrl) {
    backdropStyle = {
      backgroundImage: `url(${bgSelection.imageUrl})`,
      backgroundSize: "cover",
      backgroundPosition: "center",
    };
  }

  return (
    <div className="w-full h-full text-white relative overflow-hidden">
      <div
        style={backdropStyle}
        className="absolute inset-0 pointer-events-none z-0"
      />
      <div className="relative z-10 w-full h-full">
        <Series>
          <Series.Sequence durationInFrames={150}>
            <Scene1 />
          </Series.Sequence>
        </Series>
      </div>
    </div>
  );
};

export default VideoComposition;
